name: Deploy to MonsterASP.NET

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore RajeshTestCICD.sln

    - name: Build
      run: dotnet build RajeshTestCICD.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./RajeshTestCICD/RajeshTestCICD.csproj -c Release -o publish

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wwwroot/
